#!/bin/bash

echo "🚀 AI Video Creator - Deployment Script"
echo "======================================"
echo ""
echo "This script will help you deploy your app with the best setup for:"
echo "✅ Hot reload on every git push"
echo "✅ Fast DNS updates (< 60 seconds)"
echo "✅ Preview URLs for every branch"
echo "✅ Automatic HTTPS"
echo ""
echo "📋 Prerequisites:"
echo "1. Create a free Vercel account at: https://vercel.com/signup"
echo "2. Run: vercel login"
echo ""
echo "Press Enter when ready to continue..."
read

# Deploy to Vercel
echo "🔧 Deploying to Vercel..."
vercel --prod

echo ""
echo "🎉 Deployment complete!"
echo ""
echo "📌 Next steps for the BEST experience:"
echo ""
echo "1. Connect to GitHub for automatic deployments:"
echo "   - Go to: https://vercel.com/dashboard"
echo "   - Click your project"
echo "   - Go to Settings > Git"
echo "   - Connect to GitHub"
echo ""
echo "2. Set up a custom domain (optional):"
echo "   - Go to Settings > Domains"
echo "   - Add your domain"
echo "   - DNS updates in < 60 seconds!"
echo ""
echo "3. Your deployment features:"
echo "   ✅ Every git push = new preview URL"
echo "   ✅ main branch = production URL"
echo "   ✅ Instant rollback to any version"
echo "   ✅ Real-time logs and analytics"
echo ""
echo "🔥 Pro tip: Install Vercel GitHub app for comments on PRs with preview links!"