#!/bin/bash

echo "🚀 Deploying Social AI Pro to Vercel"
echo "===================================="
echo ""
echo "📋 Steps:"
echo "1. Run: vercel login"
echo "2. Choose your preferred login method (GitHub recommended)"
echo "3. After login, run: vercel --prod"
echo "4. Follow the prompts:"
echo "   - Set up and deploy? Y"
echo "   - Which scope? (select your account)"
echo "   - Link to existing project? N"
echo "   - Project name? social-ai-pro"
echo "   - Directory? ./"
echo "   - Override settings? N"
echo ""
echo "5. You'll get a URL like: https://social-ai-pro.vercel.app"
echo ""
echo "6. To add social-ai.pro domain:"
echo "   - Visit: https://vercel.com/dashboard"
echo "   - Click your project"
echo "   - Go to Settings → Domains"
echo "   - Add 'social-ai.pro'"
echo ""
echo "Ready? Press Enter to see the commands..."
read

echo ""
echo "📌 Command 1:"
echo "vercel login"
echo ""
echo "📌 Command 2 (after login):"
echo "vercel --prod"
echo ""
echo "That's it! Your site will be live in seconds!"